version: '3.8'
services:
  cpp-dev:
    build: 
      context: .
      platform: linux/amd64  # Force Intel emulation for student compatibility
    image: cpp-course:latest
    volumes:
      - .:/home/student/workspace
      - cpp-build-cache:/home/student/workspace/build
    working_dir: /home/student/workspace
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
    platform: linux/amd64    # Ensure consistent environment

volumes:
  cpp-build-cache: